#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$HOME/.composer/vendor/bin:$PATH"
NPM_PACKAGES="${HOME}/.npm-global/bin"
PATH="$NPM_PACKAGES:$PATH";

alias d=drush
alias gs="git status"
alias c=clear
alias v=nvim
alias gps="git push origin master"
alias gpl="git pull --rebase"
alias sv="sudo nvim"
eval "$(thefuck --alias)"

if [ -n "${NVIM_LISTEN_ADDRESS+x}" ]; then
  alias h='nvr -o'
  alias v='nvr -O'
  alias t='nvr --remote-tab'
fi


