#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$HOME/.composer/vendor/bin:$PATH"
NPM_PACKAGES="${HOME}/.npm-global/bin"
PATH="$NPM_PACKAGES:$PATH";

alias d=drush
alias gs="git status"
alias c=clear
alias v=nvim
alias gps="git push origin master"
alias gpl="git pull --rebase"
alias sv="sudo nvim"
alias dc="docker-compose"
alias dcu="docker-compose up -d"
alias dcd="docker-compose down"
alias dcp="docker-compose exec php --user 82 sh"
eval "$(thefuck --alias)"




export NVM_DIR="/home/yogevp/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
